### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by stas256** [StanislavPetrovV/Raycasting-3d-game-tutorial#1]
I try to use this code, but I got an error: 
"Traceback (most recent call last):
  File "game.py", line 26, in <module>
    drawing.world(player.pos, player.angle)
  File "C:\Users\User\Desktop\drawing.py", line 24, in world
    ray_casting(self.sc, player_pos, player_angle, self.textures)
  File "C:\Users\User\Desktop\ray_casting.py", line 49, in ray_casting
    wall_column = textures[texture].subsurface(offset * TEXTURE_SCALE, 0, TEXTURE_SCALE, TEXTURE_HEIGHT)
ValueError: subsurface rectangle outside surface area"

Please, help me

**Comment by hacker-profi** [comment]
I try to use this code, but I got an error:
"Traceback (most recent call last):
File "game.py", line 26, in
drawing.world(player.pos, player.angle)
File "C:\Users\User\Desktop\drawing.py", line 24, in world
ray_casting(self.sc, player_pos, player_angle, self.textures)
File "C:\Users\User\Desktop\ray_casting.py", line 49, in ray_casting
wall_column = textures[texture].subsurface(offset * TEXTURE_SCALE, 0, TEXTURE_SCALE, TEXTURE_HEIGHT)
ValueError: subsurface rectangle outside surface area"

Please, help me
